In [1]:
import pandas as pd
import numpy as np

In [2]:
from clean_data import cleanData

In [3]:
df = pd.read_csv(r'C:\Kenil Ramani\QB\GoalBot\CSV\v_1.17 pactive.csv')
# print(df.to_string())

In [4]:
df.head(10)

invoiceDate  quarter  month  year  day_of_week  day_of_month  day_of_year  \
0   4/12/2023        2      4  2023            4            12          102   
1   4/12/2023        2      4  2023            4            12          102   
2    2/7/2023        1      2  2023            3             7           38   
3    2/7/2023        1      2  2023            3             7           38   
4    2/7/2023        1      2  2023            3             7           38   
5    2/7/2023        1      2  2023            3             7           38   
6    2/7/2023        1      2  2023            3             7           38   
7   5/15/2023        2      5  2023            2            15          135   
8   5/15/2023        2      5  2023            2            15          135   
9    6/7/2023        2      6  2023            4             7          158   

   week_of_year  salesDetails_id  billAmount  ...  newsalesdetails_mrp  qty  \
0            15             9574      136402  ...                63.99   50   
1            15             9609      136402  ...               162.00    4   
2             6             3732        2249  ...                79.20    0   
3             6             3744        2249  ...               108.00    0   
4             6             3745        2249  ...               126.00    2   
5             6             3752        2249  ...               129.70    6   
6             6             3753        2249  ...               415.80    0   
7            20            12956      131763  ...               144.00   20   
8            20            12966      131763  ...                90.00   20   
9            23            15048       71290  ...                69.30   50   

   free    rate   amount  productId  divisionId  packingTypeId    mrp  \
0     0   41.14  2057.00      208.0         3.0           28.0   69.0   
1     6  104.14   416.56      265.0         3.0           28.0  162.0   
2     2   50.91     0.00      169.0         3.0           28.0   85.5   
3     4   69.43     0.00      213.0         3.0           28.0  117.0   
4     1   76.88   153.76        2.0         3.0           28.0  135.0   
5     4   83.38   500.28      251.0         3.0           28.0  141.3   
6     2  267.30     0.00      253.0         3.0           28.0  450.0   
7     0   92.57  1851.40       13.0         1.0           42.0  158.4   
8     0   57.86  1157.20      172.0         3.0           28.0   90.0   
9     0   44.55  2227.50        8.0         3.0           28.0   69.3   

   packingTypeId.1  
0             28.0  
1             28.0  
2             28.0  
3             28.0  
4             28.0  
5             28.0  
6             28.0  
7             42.0  
8             28.0  
9             28.0  

[10 rows x 26 columns]

In [5]:
df['invoiceDate'] = pd.to_datetime(df['invoiceDate'], errors='coerce')

In [6]:
# df['productId'] = df['productId'].round().astype('int64')    # gives error if NaN value is there
df['productId'] = df['productId'].round().astype('Int64')      # does not give error due to Int

In [7]:
df.shape

(119466, 26)

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119466 entries, 0 to 119465
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   invoiceDate          119466 non-null  datetime64[ns]
 1   quarter              119466 non-null  int64         
 2   month                119466 non-null  int64         
 3   year                 119466 non-null  int64         
 4   day_of_week          119466 non-null  int64         
 5   day_of_month         119466 non-null  int64         
 6   day_of_year          119466 non-null  int64         
 7   week_of_year         119466 non-null  int64         
 8   salesDetails_id      119466 non-null  int64         
 9   billAmount           119466 non-null  int64         
 10  stockistId           76002 non-null   float64       
 11  chemistId            43464 non-null   float64       
 12  categoryId           33325 non-null   float64       
 13  hqId          

In [9]:
df.isnull().sum()

invoiceDate                0
quarter                    0
month                      0
year                       0
day_of_week                0
day_of_month               0
day_of_year                0
week_of_year               0
salesDetails_id            0
billAmount                 0
stockistId             43464
chemistId              76002
categoryId             86141
hqId                   12983
regionId               12983
cityId                  8764
newsalesdetails_mrp        0
qty                        0
free                       0
rate                       0
amount                     0
productId              21861
divisionId             21861
packingTypeId          21861
mrp                    21861
packingTypeId.1        21861
dtype: int64

In [10]:
df.drop(columns= ['categoryId', 'cityId'], inplace = True)

50 unique stockistId;  43464 null 

In [11]:
df['stockistId'].unique()

array([111., 100.,  93.,  98., 102.,  92., 101.,  91., 105., 129.,  86.,
        87., 176., 112., 170.,  85., 199.,  97., 143., 169.,  96., 119.,
       177., 168., 184., 172.,  nan, 171., 118., 115., 197., 130., 122.,
       113., 174., 126.,  99., 131., 150., 110., 196., 204., 117., 198.,
        90.,  95., 146., 124., 193., 116.])

329 unique chemistId, 76002 null

In [12]:
df['chemistId'].unique()

array([   nan, 11062.,  5771.,  5454.,  2077.,  5412.,  5411.,  5252.,
         809.,   710.,  8079.,  2758.,   899.,  1482.,  5676.,  7432.,
        2928.,   825.,  1278.,   817.,  5236.,  2178.,   894.,  5225.,
        8856.,  2554.,  5694.,  8734.,  3621.,   992., 10961.,   839.,
         756.,  3891.,  7416.,  2558.,  5224.,  5533.,   682.,   836.,
        3660.,   752.,  8830.,  2934.,  5769.,   926.,  5757.,  5445.,
        9155.,  2174.,  4398.,  1745.,  3343.,   802.,  4360.,  6987.,
         732.,  4124.,  5331.,  1763.,   932.,  2155.,   846.,  4391.,
        5786.,  7296.,  6403.,  5483.,  5742.,  5341.,  2606.,  5432.,
        1272.,   903.,   982.,  5773.,  3523.,   872.,  5417.,   722.,
         795.,  5441.,  1281.,  1053.,   789.,  5474.,  1839.,  1171.,
        5363.,  3525.,  1047.,  5720.,  6637.,  5705.,   850.,  7970.,
         851.,  4560.,  5440.,  1070.,  2088.,  1279.,  5473.,   949.,
        2328.,  1369.,  1177.,  1747.,  5239.,  9339., 11025.,   876.,
      

142 unique productId;  21861 null

In [13]:
df['productId'].unique()                           

<IntegerArray>
[  208,   265,   169,   213,     2,   251,   253,    13,   172,     8,
 ...
 17371, 17368,    39, 17262, 17236, 17366, 17322,  <NA>,   186, 17362]
Length: 142, dtype: Int64

In [14]:
df['productId'].notna().sum()                       # null productId--> 21861

np.int64(97605)

In [15]:
# df['cityId'].isna().sum()

In [16]:
# df['cityId'].unique()                              # 79 unique cityId

In [17]:
df['amount'].unique()                              # 5538 unique

array([ 2057.  ,   416.56,     0.  , ..., 10081.68,  5104.  ,    20.  ])

In [18]:
df['mrp'].unique()                                 # 67 unique

array([ 69.  , 162.  ,  85.5 , 117.  , 135.  , 141.3 , 450.  , 158.4 ,
        90.  ,  69.3 , 247.5 , 216.  ,  72.  , 171.  ,  78.22, 157.5 ,
        99.  ,  54.  , 855.  ,  59.4 ,  79.2 , 148.5 , 720.  , 126.  ,
       108.  ,  35.64, 180.  ,  65.34,  75.6 ,  36.  , 243.  , 193.5 ,
       297.  , 138.6 , 264.6 ,  64.8 ,  81.  , 238.5 , 198.  ,  43.2 ,
        49.5 , 148.8 , 192.  ,  79.16,  63.  , 486.  , 132.  , 396.  ,
       252.  , 144.  , 177.3 ,  32.67, 495.  ,  75.4 , 288.  , 169.2 ,
       149.4 , 100.  ,  47.52, 138.42, 477.  ,  32.4 , 810.  , 169.  ,
       369.  ,  39.6 ,    nan])

In [19]:
# pd.get_dummies(df['categoryId'],drop_first=True)

StockistId where hqId is missing

In [20]:
def null(df):

    # Filter rows where any of the key location IDs are missing
    missing = df[df[['hqId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['stockistId', 'hqId']].drop_duplicates().reset_index(drop=True)

    return result
new_df = null(df)
print(new_df.to_string())

   stockistId  hqId
0       100.0   NaN
1       168.0   NaN
2         NaN   NaN
3       197.0   NaN
4        95.0   NaN


In [21]:
cd = cleanData(df)
cd.filter_productsby(productId = [283], customerType='stockist')
# cd.filter_productsby(customerType='stockist')

cd.aggregate_sales(
    frequency='weekly'
)

In [22]:
# cd.data_df

In [23]:
cd.data_df['productId'].value_counts()

productId
283    172
Name: count, dtype: Int64

In [24]:
cd.data_df

year  week_of_year  productId  qty    amount    rate invoiceDate
0    2021             1        283  420  34595.40   82.37  2021-01-01
1    2021             2        283  205  16885.85   82.37  2021-01-04
2    2021             3        283   80   6589.60   82.37  2021-01-11
3    2021             4        283  420  34595.40   82.37  2021-01-18
4    2021             5        283  260  21416.20   82.37  2021-01-25
..    ...           ...        ...  ...       ...     ...         ...
167  2024            13        283   60   6589.20  109.82  2024-03-28
168  2024            14        283  198  21744.36  109.82  2024-03-31
169  2024            15        283  213  23391.66  109.82  2024-04-08
170  2024            16        283   90   9883.80  109.82  2024-04-17
171  2024            17        283  307  33714.74  109.82  2024-04-22

[172 rows x 7 columns]

In [25]:
X = cd.data_df.drop('amount', axis=1)
y = cd.data_df['amount']

In [26]:
X

year  week_of_year  productId  qty    rate invoiceDate
0    2021             1        283  420   82.37  2021-01-01
1    2021             2        283  205   82.37  2021-01-04
2    2021             3        283   80   82.37  2021-01-11
3    2021             4        283  420   82.37  2021-01-18
4    2021             5        283  260   82.37  2021-01-25
..    ...           ...        ...  ...     ...         ...
167  2024            13        283   60  109.82  2024-03-28
168  2024            14        283  198  109.82  2024-03-31
169  2024            15        283  213  109.82  2024-04-08
170  2024            16        283   90  109.82  2024-04-17
171  2024            17        283  307  109.82  2024-04-22

[172 rows x 6 columns]

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
X_train

year  week_of_year  productId  qty    rate invoiceDate
66   2022            15        283  377   87.86  2022-04-05
160  2024             6        283  519  109.82  2024-02-06
11   2021            12        283  162   82.37  2021-03-15
69   2022            18        283   80   87.86  2022-04-28
163  2024             9        283  536  109.82  2024-02-28
..    ...           ...        ...  ...     ...         ...
71   2022            20        283   55   87.86  2022-05-10
106  2023             3        283  132   87.86  2023-01-20
14   2021            15        283  280   82.37  2021-04-05
92   2022            42        283   59   87.86  2022-10-10
102  2022            52        283  110   87.86  2022-12-20

[115 rows x 6 columns]

In [29]:
# X_train['year'] = pd.to_datetime(X_train['year'], errors='coerce')

X_train['invoice_year'] = X_train['invoiceDate'].dt.year
X_train['invoice_month'] = X_train['invoiceDate'].dt.month
X_train['invoice_day'] = X_train['invoiceDate'].dt.day
X_train['invoice_weekday'] = X_train['invoiceDate'].dt.weekday

# Then drop the original datetime column
X_train = X_train.drop(columns=['invoiceDate'])


In [30]:
# X_train['week_of_year'] = pd.to_datetime(X_train['week_of_year'], errors='coerce')

X_test['invoice_year'] = X_test['invoiceDate'].dt.year
X_test['invoice_month'] = X_test['invoiceDate'].dt.month
X_test['invoice_day'] = X_test['invoiceDate'].dt.day
X_test['invoice_weekday'] = X_test['invoiceDate'].dt.weekday

X_test = X_test.drop(columns=['invoiceDate'])


In [31]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115 entries, 66 to 102
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   year             115 non-null    int32  
 1   week_of_year     115 non-null    int64  
 2   productId        115 non-null    Int64  
 3   qty              115 non-null    int64  
 4   rate             115 non-null    float64
 5   invoice_year     115 non-null    int32  
 6   invoice_month    115 non-null    int32  
 7   invoice_day      115 non-null    int32  
 8   invoice_weekday  115 non-null    int32  
dtypes: Int64(1), float64(1), int32(5), int64(2)
memory usage: 6.9 KB


In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=10, max_depth=12)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [33]:
print("MSE:", mean_squared_error(y_test, y_pred))               # MSE tells you how far off your predictions are; lower the better
print("R²:", r2_score(y_test, y_pred))                          # R² tells you how useful the model is

###
r2 = r2_score(y_test, y_pred)
accuracy_percentage = r2 * 100
print("Model Accuracy (%):", accuracy_percentage)

MSE: 4184904.9068638613
R²: 0.9658322874113395
Model Accuracy (%): 96.58322874113395
